print(" *** Bienvenidos, vamos a validar como funciona una aplicacion de control de versiones ***")
print(" *** A continuacion podra comprobar el resultado de diversas operaciones matematicas")
print(6 // 3)
print(6 // 3.)
print(6. // 3)
print(6. // 3.)